# GolangCI-Lint configuration file
# Docs: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 2m
  concurrency: 4
  tests: false

linters:
  disable:
    - unused
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - gocyclo
    - govet
  settings:
    staticcheck:
      checks:
        - all
        - -QF1001
        - -QF1004
        - -QF1006
        - -QF1008
        - -ST1000
        - -ST1001
        - -ST1003
        - -ST1021
    gocyclo:
      min-complexity: 50
