// Package textx GENERATED BY code_error DO NOT EDIT
package textx

import (
	"fmt"
)

func (e Ecode) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[textx:%d] unknown", e)
	case ECODE_UNDEFINED:
		return "[textx:0] undefined"
	case ECODE__MARSHAL_TEXT_INVALID_INPUT:
		return "[textx:1] marshal text got invalid input"
	case ECODE__MARSHAL_TEXT_FAILED:
		return "[textx:2] failed to marshal text"
	case ECODE__MARSHAL_URL_INVALID_INPUT:
		return "[textx:3] marshal url got invalid input"
	case ECODE__MARSHAL_URL_FAILED:
		return "[textx:4] failed to marshal url"
	case ECODE__UNMARSHAL_TEXT_INVALID_INPUT:
		return "[textx:5] unmarshal text got invalid input"
	case ECODE__UNMARSHAL_TEXT_FAILED:
		return "[textx:6] failed to unmarshal text"
	case ECODE__UNMARSHAL_URL_INVALID_INPUT:
		return "[textx:7] unmarshal url got invalid input"
	case ECODE__UNMARSHAL_URL_FAILED:
		return "[textx:8] failed to unmarshal url"
	}
}
