// Package reflectx GENERATED BY code_error DO NOT EDIT
package reflectx

import (
	"fmt"
)

func (e Ecode) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[PARSING_TAG:%d] unknown", e)
	case ECODE_UNDEFINED:
		return "[PARSING_TAG:0] undefined"
	case ECODE__INVALID_FLAG_KEY:
		return "[PARSING_TAG:1] invalid flag key"
	case ECODE__INVALID_FLAG_VALUE:
		return "[PARSING_TAG:2] invalid flag value"
	case ECODE__INVALID_FLAG_NAME:
		return "[PARSING_TAG:3] invalid flag flag name"
	case ECODE__INVALID_OPTION_KEY:
		return "[PARSING_TAG:4] invalid option key"
	case ECODE__INVALID_OPTION_VALUE:
		return "[PARSING_TAG:5] invalid option value"
	case ECODE__INVALID_OPTION_UNQUOTED:
		return "[PARSING_TAG:6] invalid option unquoted"
	}
}
